package appspot.com.cargiver;

import java.util.List;

/**
 * Created by GK on 11/24/2017.
 */

// Supervisor is identified in the DB by UID provided to the user by firebase

public class Supervisor {
    List<Car> carsOwned;
    List<String> drivesIDs; // keys of drives related to the supervisor (key as generated by firebase)
    List<String> pendingDriversIDs; // the key of the drivers pending
    List<String> authorizedDriversIDs; // the key of the authorized drivers

    public Supervisor() {
        // Default constructor required for calls to DataSnapshot.getValue(Supervisor.class)
    }
}
