package appspot.com.cargiver;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

/**
 * Created by GK on 11/24/2017.
 */

// Supervisor is identified in the DB by UID provided to the user by firebase

public class Supervisor {
    List<String> drivesIDs; // keys of drives related to the supervisor (key as generated by firebase)
    List<String> pendingDriversIDs; // the key of the drivers pending
    HashMap<String,Boolean> authorizedDriversIDs; // the key of the authorized drivers

    public Supervisor() {
        // Default constructor required for calls to DataSnapshot.getValue(Supervisor.class)
    }

    public Supervisor(String authorizedDriver1){
        // Temporary constructor
        //this.authorizedDriversIDs = new ArrayList<>(Arrays.asList(authorizedDriver1));
    }

    public Supervisor(String authorizedDriver1, String authorizedDriver2){
        // Temporary constructor
        //this.authorizedDriversIDs = new ArrayList<>(Arrays.asList(authorizedDriver1, authorizedDriver2));
    }

}
